# Integration test container for Fedora 41.
ARG BASE=fedora:41
FROM ${BASE}

RUN dnf install -y --setopt=install_weak_deps=False \
        sudo ca-certificates coreutils \
 && dnf clean all

RUN useradd -m -s /bin/bash sudotest \
 && useradd -m -s /bin/bash sudopwd \
 && echo 'sudopwd:sudopwd' | chpasswd

RUN printf '%s\n' \
        'Defaults    env_keep += "SUDOCONSOLE_PASSWORD SUDOCONSOLE_CONFIG SUDOCONSOLE_AUDIT_LOG"' \
        'Defaults    timestamp_timeout=0' \
        'sudotest    ALL=(ALL) NOPASSWD: ALL' \
        'sudopwd     ALL=(ALL) ALL' \
        > /etc/sudoers.d/sudoconsole-test \
 && chmod 0440 /etc/sudoers.d/sudoconsole-test

USER sudotest
WORKDIR /home/sudotest

ENTRYPOINT ["/bin/integration.test"]
CMD ["-test.v"]