# Integration test container for Arch Linux (latest).
ARG BASE=archlinux:latest
FROM ${BASE}

RUN pacman -Sy --noconfirm --needed \
        sudo ca-certificates coreutils \
 && pacman -Scc --noconfirm

RUN useradd -m -s /bin/bash sudotest \
 && useradd -m -s /bin/bash sudopwd \
 && echo 'sudopwd:sudopwd' | chpasswd

RUN printf '%s\n' \
        'Defaults    env_keep += "SUDOCONSOLE_PASSWORD SUDOCONSOLE_CONFIG SUDOCONSOLE_AUDIT_LOG HOME XDG_CONFIG_HOME XDG_DATA_HOME"' \
        'Defaults    !set_home' \
        'Defaults    timestamp_timeout=0' \
        'sudotest    ALL=(ALL) NOPASSWD: ALL' \
        'sudopwd     ALL=(ALL) ALL' \
        > /etc/sudoers.d/sudoconsole-test \
 && chmod 0440 /etc/sudoers.d/sudoconsole-test

COPY --from=artifacts sudoconsole /usr/local/bin/sudoconsole
COPY --from=artifacts integration.test /usr/local/bin/integration.test
RUN chmod +x /usr/local/bin/sudoconsole /usr/local/bin/integration.test

USER sudotest
WORKDIR /home/sudotest

ENTRYPOINT ["/usr/local/bin/integration.test"]
CMD ["-test.v"]